### PR TITLE
Update to the revamped rock-gazebo integration

### PR DESCRIPTION
**Pull request by doudou**
This is the result of last Wednesday's work.

@alexfneves when you have the time, I would appreciate it if you switched to this buildconf.

To switch in-place, run

~~~
autoproj switch-config branch=rock-gazebo
~~~

There might be some packages that do not update cleanly. If they are rock packages that you haven't worked on, just `git reset --hard` them. For your packages, I let you be the judge ;-)

### CODE REVIEW

**Comment by alexfneves** [comment]
On monday I was trying the aup/amake, but I had an issue on the rock_widget_collection. I was on the make_qwt5_optional branch instead of master. I changed:

src/CMakeLists.txt
```
-    add_definition(-DUSE_QWT)
+    add_definitions(-DUSE_QWT)
```
src/RockWidgetCollection.cc
```
 #include "sonar_widget/SonarWidgetPlugin.h"
+#include "artificial_horizon/compassplugin.h"
 
 #ifdef USE_VTK
```

I don't have permission on this package so I couldn't push.

Then I had an issue on the control_ui package and heads_smac. They were using the external/yaml-cpp on the old-API and it looked like the external/yaml-cpp was now the new API. For some reason yesterday the aup amake was normal again, like the yaml was using the old API again.

Now, I just used the `autoproj switch-config branch=rock-gazebo`, then aup amake and nothing went wrong. As a note, I have a branch from the fork on the rock-gazebo with 4 commits but I switched to the master for the aup to work.

**Comment by doudou** [comment]
> For some reason yesterday the aup amake was normal again, like the yaml was using the old API again.

When you say "was" ... was it before last week ? I might have removed the external/yaml-cpp from your workspace last week.

**Comment by doudou** [comment]
It seems that I forgot to test the make_qwt5_optional branch when QWT is there :(. I'll fix that.

**Comment by doudou** [comment]
QWT problem fixed and pushed. Note that I've amended the last commit, so you'll need to manually
reset your clone to the new tip of the branch, aup will refuse updating.

**Comment by alexfneves** [comment]
Changed the make_qwt5_optional branch and the aup/amake worked.

On last weeks's wednesday the aup/amake worked in Rio Comprido, and the external/yaml-cpp was there, on monday aup/amake didn't work, and then yesterday it was normal again. No idea what exactly happened with the external/yaml-cpp, but it is working now so it's fine.

**Comment by doudou** [comment]
OK. @erizzoalbuquerque, do you have a bootstrap of the install, or may I merge this ?

**Comment by erizzoalbuquerque** [comment]
You can marge. Thank you!

**Pull request merged**
